from setuptools import setup, find_packages

setup(
    name="asan-ai-safety",
    version="0.1.0",
    description="Adaptive Spectral Alignment Networks for Predictive AI Safety",
    author="Sibi Vishtan Thirukonda",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "numpy>=1.24.0",
        "pywt>=1.4.1",
        "matplotlib>=3.7.0",
        "plotly>=5.14.0",
        "dash>=2.11.0",
        "pandas>=2.0.0",
        "accelerate>=0.20.0",
        "datasets>=2.12.0",
        "tokenizers>=0.13.0",
        "scikit-learn>=1.2.0",
        "scipy>=1.10.0",
        "tqdm>=4.65.0",
        "tensorboard>=2.12.0",
        "jupyter>=1.0.0",
        "pytest>=7.3.0",
        "seaborn>=0.12.0",
        "dash-bootstrap-components>=1.4.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
